var main = { 
    castString: ()=> {
        console.log('---- String() ----')
       console.log(`String(1) >> ${String(1)}`)
       console.log(`String(NaN) >> ${String(NaN)}`)
       console.log(`String(Infinity) >> ${String(Infinity)}`)
       console.log(`String(false) >> ${String(false)}`)
       console.log(`String(true) >> ${String(true)}`)
       console.log(`\n`)
       console.log('---- ().toString ----')
       console.log(`(1).toString >> ${(1).toString}`)
       console.log(`(NaN).toString >> ${(NaN).toString}`)
       console.log(`(Infinity).toString >> ${(Infinity).toString}`)
       console.log(`(false).toString >> ${(false).toString}`)
       console.log(`(true).toString >> ${(true).toString}`)
       console.log(`\n`)
       console.log(`---- + '' ----`)
       console.log(`1+'' >> ${1+''}`)
       console.log(`NaN+'' >> ${NaN+''}`)
       console.log(`Infinity+'' >> ${Infinity+''}`)
       console.log(`false+'' >> ${false+''}`)
       console.log(`true+'' >> ${true+''}`)
       console.log(`\n`)
    },
    castNumber : ()=>{
        console.log('---- Nubmer() ----')
        console.log(`Nubmer('0') >> ${Nubmer('0')}`)
        console.log(`Nubmer('-1') >> ${Nubmer('-1')}`)
        console.log(`Nubmer('10.53') >> ${Nubmer('10.53')}`)
        console.log(`Nubmer(false) >> ${Number(false)}`)
        console.log(`Nubmer(true) >> ${Number(true)}`)
        console.log(`\n`)
        console.log('---- parseInt() ----')
        console.log(`parseInt('0') >> ${parseInt('0')}`)
        console.log(`parseInt('-1') >> ${parseInt('-1')}`)
        console.log(`parseInt('10.53') >> ${parseInt('10.53')}`)
        console.log(`parseInt(true) >> ${parseInt(true)}`)
        console.log(`parseInt(false) >> ${parseInt(false)}`)
        console.log(`\n`)
        console.log(`---- 산술연산자 ----`)
        console.log(`'0' * 1 >> ${'0' * 1}`)
        console.log(`'-1' * 1 >> ${'-1' * 1}`)
        console.log(`'10.53' * 1 >> ${'10.53' * 1}`)
        console.log(`false*1 >> ${false*1}`)
        console.log(`true*1 >> ${true*1}`)
        console.log(`\n`)
    },
    castBoolean : ()=>{
        console.log('---- Nubmer() ----')
        console.log(`Nubmer('0') >> ${Nubmer('0')}`)
        console.log(`Nubmer('-1') >> ${Nubmer('-1')}`)
        console.log(`Nubmer('10.53') >> ${Nubmer('10.53')}`)
        console.log(`Nubmer(false) >> ${Number(false)}`)
        console.log(`Nubmer(true) >> ${Number(true)}`)
        console.log(`\n`)
        console.log('---- parseInt() ----')
        console.log(`parseInt('0') >> ${parseInt('0')}`)
        console.log(`parseInt('-1') >> ${parseInt('-1')}`)
        console.log(`parseInt('10.53') >> ${parseInt('10.53')}`)
        console.log(`parseInt(true) >> ${parseInt(true)}`)
        console.log(`parseInt(false) >> ${parseInt(false)}`)
        console.log(`\n`)
        console.log(`---- 산술연산자 ----`)
        console.log(`'0' * 1 >> ${'0' * 1}`)
        console.log(`'-1' * 1 >> ${'-1' * 1}`)
        console.log(`'10.53' * 1 >> ${'10.53' * 1}`)
        console.log(`false*1 >> ${false*1}`)
        console.log(`true*1 >> ${true*1}`)
        console.log(`\n`)

    }
}